[package]
name = "tea-reth"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true

[[bin]]
name = "tea-reth"
path = "src/main.rs"

[dependencies]
# reth
reth-cli-util.workspace = true
reth-op = { workspace = true, features = ["node", "rpc"] }
reth-optimism-cli.workspace = true

# tea
tea-precompiles.workspace = true

# misc
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
tracing.workspace = true

[dev-dependencies]
tea-precompiles = { workspace = true }
alloy-evm.workspace = true
alloy-op-evm.workspace = true
alloy-primitives = { workspace = true, features = ["std"] }
op-revm.workspace = true
revm.workspace = true
hex = "0.4.3"

[features]
default = []
